pipeline {
    agent any

    

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Terraform Deploy') {
            steps {
                dir('terraform') {
                    sh 'terraform init'
                    sh 'terraform plan -var="ami_id=ami-0abc1234def567890"'
                    sh 'terraform apply -var="ami_id=ami-0abc1234def567890" -auto-approve'

                }
            }
        }
    }
}
