aws_region             = "us-east-1"
ami_id                 = "ami-0b6c6ebed2801a5cb"
instance_type          = "t2.micro"
allowed_ssh_cidr       = "0.0.0.0/0"
existing_key_pair_name = "your-keypair-name"
